### ISSUE TITLE
Feature request: YAML feed URL configuration

### ISSUE THREAD

**Issue by jinnovation** [akrennmair/newsbeuter#158]
IMO, URL configuration would be well-served with syntax similar to the following:

``` YAML
- <feed URL>
  - tags: <tag1>, <tag2>, <tag3>
  - name: <name to display in feed list>
```
